In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
x=np.array([1,2,3,4,5])

In [6]:
print(x)

[1 2 3 4 5]


In [7]:
y=np.arange(10)

In [8]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
alist=[1,2,3,4,4]
print(type(alist))

<class 'list'>


### Compare Runtime Excution List vs Array

In [10]:
%timeit [j**4 for j in range(1,20)]

9.94 µs ± 572 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
%timeit [np.arange(1,20)**4]

9.46 µs ± 1.52 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Creating Numpy Array

In [12]:
Array=np.array([1,2,3])
print(Array)

[1 2 3]


In [13]:
l=[]
for i in range(1,5):
    int_1=int(input("Enter Number: "))
    l.append(int_1)
print(l)

Enter Number: 12
Enter Number: 34
Enter Number: 5
Enter Number: 6
[12, 34, 5, 6]


## Dimension in Array

- 1-Dimension Array
- 2-Dimension Array
- 3-Dimension Array
- n-Dimension Array

In [18]:
# One Dimension Array
arr1=np.array([1,2,3])
print(arr1)
print("Type of Array is :",arr1.ndim)

[1 2 3]
Type of Array is : 1


In [19]:
# Two Dimension Array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print("Type of Array is :",arr2.ndim)

[[1 2 3]
 [4 5 6]]
Type of Array is : 2


In [20]:
# Three Dimension Array
arr3=np.array([[[1,2,3],[4,5,6]]])
print(arr3)
print("Type of Array is :",arr3.ndim)

[[[1 2 3]
  [4 5 6]]]
Type of Array is : 3


In [21]:
# Ten Dimension Array
 arr10=np.array([1,2,3,4] ,ndim=12)
print(arr10)
print("Type of Array is :",arr10.ndim)

IndentationError: unexpected indent (3185665849.py, line 2)

### Special Numpy Array

In [ ]:
# Zero Array
ar_zero=np.zeros(10)
print(ar_zero)
ar_zero2=np.zeros((2,4))
print(ar_zero2)

In [ ]:
# One Array
ar_one=np.ones(10)
print(ar_one)
ar_one2=np.ones((2,4))
print(ar_one2)

In [22]:
# Empty Array
arr_emp=np.empty(10)
print(arr_emp)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.29060871e-306
 1.89146896e-307 7.56571288e-307 3.11525958e-307 1.24610723e-306
 1.29061142e-306 5.53353523e-322]


In [23]:
# Range Array
arr_ran=np.arange(1,11).reshape(2,5)
print(arr_ran)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
# Diagonal Array
arr_dig=np.eye(3,4)
print(arr_dig)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [25]:
# Linespace Array
lin_arr=np.linspace(1,20,num=8)
print(lin_arr)

[ 1.          3.71428571  6.42857143  9.14285714 11.85714286 14.57142857
 17.28571429 20.        ]


### Numpy Random Number

In [26]:
# Randn Function
var=np.random.rand(4)
print(var)

[0.87834485 0.96036137 0.06783498 0.32171248]


In [27]:
var1=np.random.rand(2,5)
print(var1)

[[0.89024198 0.22577287 0.3446152  0.98136788 0.6283512 ]
 [0.44312265 0.42565482 0.38292755 0.74277772 0.70471348]]


In [28]:
# Randn function
jar=np.random.randn(5)
print(jar)

[-0.66328781  0.58437165  1.33588827  0.04493799 -0.84308466]


In [29]:
jar1=np.random.randn(3,5)
print(jar1)

[[ 0.26113204 -0.77670824  0.332158   -0.00404194  0.45502835]
 [-0.86984169  0.53462753 -0.27286873 -0.27225769  0.64545642]
 [-0.80389127 -0.09507209  1.06770495 -0.51135225  0.69457924]]


In [30]:
# Randf function
bar=np.random.ranf(6)
print(bar)

[0.16311505 0.17330994 0.29018939 0.35531007 0.77868442 0.19806334]


In [31]:
bar1=np.random.ranf((2,3))
print(bar1)

[[0.76864457 0.6638815  0.67883579]
 [0.68464483 0.09450336 0.08757991]]


In [32]:
# Randint function
car=np.random.randint(12,20,20)
print(car)

[17 18 15 17 13 17 12 18 14 13 16 15 12 13 17 14 18 17 17 16]


In [33]:
car1=np.random.randint(12,20,20).reshape(2,10)
print(car1)

[[17 12 18 16 12 16 18 19 12 12]
 [12 13 19 14 14 13 18 14 18 19]]


### Data Type

In [34]:
# var=np.array([1,2,4,5])
print(var,"Data type:",var.dtype)

[0.87834485 0.96036137 0.06783498 0.32171248] Data type: float64


In [35]:
var=np.array([1.1,2,4,5])
print(var,"Data type:",var.dtype)

[1.1 2.  4.  5. ] Data type: float64


In [36]:
var=np.array(['A','B','C'])
print(var,"Data type:",var.dtype)

['A' 'B' 'C'] Data type: <U1


In [37]:
var=np.array(['A','B','C',1,2,3])
print(var,"Data type:",var.dtype)

['A' 'B' 'C' '1' '2' '3'] Data type: <U11


In [38]:
x=np.array([1,2,3,4],dtype=np.int32)
print(x,"Data type:",x.dtype)

[1 2 3 4] Data type: int32


## Arithematic Operation

In [39]:
# Addition
var=np.array([1,2,44])
var1=var+2
print(var1)
var2=np.array([23,56,34])
print(np.add(var,var2))

[ 3  4 46]
[24 58 78]


In [40]:
# Subtraction
var=np.array([1,2,44])
var1=var-2
print(var1)
var2=np.array([23,56,34])
print(np.subtract(var,var2))

[-1  0 42]
[-22 -54  10]


In [41]:
# Multiplication
var=np.array([1,2,44])
var1=var*2
print(var1)
var2=np.array([23,56,34])
print(np.multiply(var,var2))

[ 2  4 88]
[  23  112 1496]


In [42]:
# Modulus
var=np.array([1,2,44])

var2=np.array([23,56,34])
print(np.mod(var,var2))

[ 1  2 10]


### Arithematic Function

In [43]:
var=np.array([1,2,3,6,7])
print("The Maximum Value is: ",np.max(var))
print("The Minimum Value is: ",np.min(var))
print("The AverageValue is: ",np.average(var))
print("The Maximum Value is: ",np.max(var))



The Maximum Value is:  7
The Minimum Value is:  1
The AverageValue is:  3.8
The Maximum Value is:  7


### Shape

In [44]:
var=np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print(var.ndim)
print(var.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


### Reshape

In [45]:
var=np.array([1,2,3,4,5,7,8,9])
print(var)
print(var.ndim)

var1=var.reshape(2,4)
print(var1)
print(var1.ndim)

[1 2 3 4 5 7 8 9]
1
[[1 2 3 4]
 [5 7 8 9]]
2


In [46]:
var=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var.reshape(2,3,2))

print(var3.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


NameError: name 'var3' is not defined

In [ ]:
var3=var.reshape(3,2,2)
print(var3)
print(var3.ndim)

### Indexing and Slicing in Numpy Array

In [47]:
var=np.array([1,2,3,4])
print(var[-1::-3])


[4 1]


In [48]:
var=np.array([1,2,3,4,5,6,7,8])
print(var[1:4:2])

[2 4]


### Iteration

In [49]:
var=np.array([1,2,3,4,5,6,7,8])
print(var)
for i in var:
    print(i)

[1 2 3 4 5 6 7 8]
1
2
3
4
5
6
7
8


In [50]:
# One Dimension Array
var2d=np.array([[1,2,3],[4,5,6]])
print(var2d)
for i in var2d:
    print(i)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]


In [51]:
# Two dimension Array
var2d=np.array([[1,2,3],[4,5,6]])
print(var2d)
for i in var2d:
    for j in i:
        print(j)
    

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


In [52]:
# Three Dimension Array
var3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(var3d)
print(var3d.shape)
print(var3d.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)
3


In [53]:
var3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in var3d:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9


### Search

In [54]:
var=np.array([1,2,4,5,7,84,5,3,6,5,6,21,5,3,6,7])
x=np.where(var==6)
print(x)

(array([ 8, 10, 14], dtype=int64),)


### Numpy Array Function

In [55]:
# Shuffle Function
var=np.array([1,2,2,34,56,7,7,8,9])
np.random.shuffle(var)
print(var)

[ 2  9  7  2 34  7  1 56  8]


In [56]:
# Unique Function
var1=np.array([1,2,2,34,34,56,7,8,9])
x=np.unique(var1)
print(x)

[ 1  2  7  8  9 34 56]


### Numpy Matrix

In [57]:
arr=np.array([[1,2,3],[5,7,8]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [5 7 8]]
<class 'numpy.ndarray'>
2


In [58]:
arr=np.matrix([[1,6,0],[1,9,2]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 6 0]
 [1 9 2]]
<class 'numpy.matrix'>
2


In [60]:
ma=np.matrix([[1,6,0],[1,9,2]])
ma1=np.matrix([[5,6,7],[6,9,1]])
print(ma+ma1)           # + - * / 

[[ 6 12  7]
 [ 7 18  3]]


In [68]:
mat=np.matrix([[1,2,5],[7,8,9]])
print(mat)
print("The Transpose of the Matrix is: ",np.transpose(mat))

[[1 2 5]
 [7 8 9]]
The Transpose of the Matrix is:  [[1 7]
 [2 8]
 [5 9]]


In [70]:
mat3=np.matrix([[4,5,6],[7,9,0],[7,8,9]])
print(np.linalg.inv(mat3))

[[-2.45454545 -0.09090909  1.63636364]
 [ 1.90909091  0.18181818 -1.27272727]
 [ 0.21212121 -0.09090909 -0.03030303]]
